
//Information type
#define ALL_DATA 0x80
#define VIN_AND_HW 0x86
#define BOOT_VERSION 0x8A
#define VIN 0x90
#define VEHICLE_ECU_HW 0x91
#define SUPPLIER_ECU_HW 0x92
#define ECU_HW_VERSION 0x93
#define SUPPLIER_ECU_SW 0x94
#define ECU_SW_VERSION 0x95
#define HOMOLOGATION_CODE 0x96
#define ISO_CODE 0x97
#define TESTER_CODE 0x97
#define REPROGRAMMING_PRODUCTION_DATE 0x99
#define CALIBRATION_DATE 0x9B
#define CALIBRATION_EQUIPMENT_SW 0x9C
